services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_vol:/data/db      


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017     
    depends_on:
      - mongo

  tests:
    container_name: container-tests
    build: 
      context: ..
      dockerfile: ./docker/test.Dockerfile
    command: bash -c "pytest"
    depends_on:
      - mongo
    env_file:
      - ../.env   

  app:
    build: 
      context: ..
      dockerfile: ./docker/dev.Dockerfile
    command: bash -c "python main.py"
    ports:
      - 8080:8080
    depends_on:
      - tests
    env_file:
      - ../.env  

volumes:
  mongodb_vol: