services:

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_vol:/data/db

  tests:
    container_name: tests
    build:
      context: ..
      dockerfile: ./docker/test.Dockerfile
    command: bash -c "coverage run --source=app -m pytest && coverage report -m"
    depends_on:
      - mongo
    env_file:
      - ../.env

volumes:
  mongodb_vol:
